export const name = 'Joel Bandi'
export const occupation = 'Software Developer'
export const location = 'Santa Barbara City'
export const company = 'Procore'
export const githubUserName = 'joelbandi'
export const linkedinUserName = 'joelbandi'
export const web = 'https://joelbandi.github.io'
export const email = 'joelvivekbandi@gmail.com'